/** Demo seed data for browser-local (localStorage) mode — mirrors server/db.js */

const now = '2026-09-29T12:00:00.000Z';

export const DEMO_USER = {
  id: 'user-1',
  email: 'admin@contractor.local',
  name: 'Admin User',
  role: 'admin',
  password: 'admin123',
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type DbRow = Record<string, any>;

export interface LocalDb {
  customers: DbRow[];
  assets: DbRow[];
  jobs: DbRow[];
  fuelLogs: DbRow[];
  maintenance: DbRow[];
  bookings: DbRow[];
  settings: {
    companyName: string;
    currency: string;
    lowFuelThresholdPercent: number;
    theme: string;
  };
}

export function createSeedDb(): LocalDb {
  const customers = [
    {
      id: 'cust-1',
      name: 'National Highways – Area 7',
      contactName: 'Sarah Mitchell',
      contactEmail: 'sarah.mitchell@nationalhighways.gov.uk',
      contactPhone: '0115 555 0142',
      address: 'Area 7 Depot, Nottingham NG9 2HQ',
      notes: 'Framework contractor for winter maintenance and resurfacing.',
      createdAt: now,
    },
    {
      id: 'cust-2',
      name: 'Lincolnshire County Council',
      contactName: 'James Thornton',
      contactEmail: 'j.thornton@lincolnshire.gov.uk',
      contactPhone: '01522 555 089',
      address: 'County Offices, Newland, Lincoln LN1 1YL',
      notes: 'Drainage and verge works across A15 corridor.',
      createdAt: now,
    },
    {
      id: 'cust-3',
      name: 'Balfour Beatty Living Places',
      contactName: 'Priya Sharma',
      contactEmail: 'priya.sharma@bblivingplaces.com',
      contactPhone: '0113 555 2201',
      address: 'Leeds Hub, LS11 5QR',
      notes: 'Sub-contract plant hire for M1 J28–J32 scheme.',
      createdAt: now,
    },
    {
      id: 'cust-4',
      name: 'Amey Highways',
      contactName: 'David Okafor',
      contactEmail: 'david.okafor@amey.co.uk',
      contactPhone: '0121 555 3344',
      address: 'Birmingham Regional Office, B1 1BB',
      notes: 'Reactive repairs and street lighting support.',
      createdAt: now,
    },
  ];

  const assets = [
    {
      id: 'asset-1',
      name: 'DAF CF Tipper 26t',
      sku: 'VEH-TIP-001',
      category: 'Vehicles',
      condition: 'Good',
      fuelTankLitres: 300,
      fuelLevelLitres: 95,
      locationLat: 52.9548,
      locationLng: -1.1581,
      locationDescription: 'Nottingham Depot – Bay 3',
      postcode: 'NG9 2HQ',
      currentJobId: 'job-1',
      jobAssignedAt: '2026-09-22T08:00:00.000Z',
      quantity: 1,
      reorderLevel: null,
      notes: 'Gritter-ready tipper. Tail-lift serviced Aug 2026.',
      createdAt: now,
    },
    {
      id: 'asset-2',
      name: 'Ford Transit Custom LWB',
      sku: 'VEH-VAN-002',
      category: 'Vehicles',
      condition: 'Excellent',
      fuelTankLitres: 70,
      fuelLevelLitres: 42,
      locationLat: 53.2307,
      locationLng: -0.5406,
      locationDescription: 'Lincoln site compound',
      postcode: 'LN1 1YL',
      currentJobId: 'job-2',
      jobAssignedAt: '2026-09-25T07:30:00.000Z',
      quantity: 1,
      reorderLevel: null,
      notes: 'Crew van – racks fitted for hand tools.',
      createdAt: now,
    },
    {
      id: 'asset-3',
      name: 'Iveco Daily Cherry Picker',
      sku: 'VEH-CP-003',
      category: 'Vehicles',
      condition: 'Good',
      fuelTankLitres: 90,
      fuelLevelLitres: 18,
      locationLat: 52.9548,
      locationLng: -1.1581,
      locationDescription: 'Nottingham Depot – Bay 1',
      postcode: 'NG9 2HQ',
      currentJobId: null,
      jobAssignedAt: null,
      quantity: 1,
      reorderLevel: null,
      notes: '17m boom. LOLER cert valid.',
      createdAt: now,
    },
    {
      id: 'asset-4',
      name: 'JCB 3CX Excavator',
      sku: 'PLT-EXC-001',
      category: 'Machinery / plant',
      condition: 'Good',
      fuelTankLitres: 115,
      fuelLevelLitres: 60,
      locationLat: 53.7997,
      locationLng: -1.5492,
      locationDescription: 'Leeds M1 compound',
      postcode: 'LS11 5QR',
      currentJobId: 'job-3',
      jobAssignedAt: '2026-09-20T06:00:00.000Z',
      quantity: 1,
      reorderLevel: null,
      notes: 'Bucket + breaker attachment available.',
      createdAt: now,
    },
    {
      id: 'asset-5',
      name: 'Bomag BW120 Roller',
      sku: 'PLT-ROL-002',
      category: 'Machinery / plant',
      condition: 'Fair',
      fuelTankLitres: 45,
      fuelLevelLitres: 30,
      locationLat: 52.9548,
      locationLng: -1.1581,
      locationDescription: 'Nottingham Depot – Plant yard',
      postcode: 'NG9 2HQ',
      currentJobId: null,
      jobAssignedAt: null,
      quantity: 1,
      reorderLevel: null,
      notes: 'Vibration module intermittent – monitor.',
      createdAt: now,
    },
    {
      id: 'asset-6',
      name: 'Atlas Copco QAS40 Generator',
      sku: 'PLT-GEN-003',
      category: 'Machinery / plant',
      condition: 'Excellent',
      fuelTankLitres: 87,
      fuelLevelLitres: 70,
      locationLat: 52.4862,
      locationLng: -1.8904,
      locationDescription: 'Birmingham staging',
      postcode: 'B1 1BB',
      currentJobId: null,
      jobAssignedAt: null,
      quantity: 1,
      reorderLevel: null,
      notes: '40 kVA diesel. Bunded tank.',
      createdAt: now,
    },
    {
      id: 'asset-7',
      name: 'Hilti TE 60-ATC Combihammer',
      sku: 'PWR-HIL-001',
      category: 'Power tools',
      condition: 'Good',
      fuelTankLitres: null,
      fuelLevelLitres: null,
      locationLat: null,
      locationLng: null,
      locationDescription: 'Tool store – Shelf A2',
      postcode: 'NG9 2HQ',
      currentJobId: 'job-2',
      jobAssignedAt: '2026-09-25T07:30:00.000Z',
      quantity: 1,
      reorderLevel: null,
      notes: 'SDS-max. PAT due Oct 2026.',
      createdAt: now,
    },
    {
      id: 'asset-8',
      name: 'Makita DGA504 Angle Grinder',
      sku: 'PWR-MAK-002',
      category: 'Power tools',
      condition: 'Excellent',
      fuelTankLitres: null,
      fuelLevelLitres: null,
      locationLat: null,
      locationLng: null,
      locationDescription: 'Tool store – Shelf B1',
      postcode: 'NG9 2HQ',
      currentJobId: null,
      jobAssignedAt: null,
      quantity: 3,
      reorderLevel: 1,
      notes: '18V cordless set of 3.',
      createdAt: now,
    },
    {
      id: 'asset-9',
      name: 'Stihl TS410 Cut-off Saw',
      sku: 'PWR-STI-003',
      category: 'Power tools',
      condition: 'Good',
      fuelTankLitres: 0.7,
      fuelLevelLitres: 0.4,
      locationLat: null,
      locationLng: null,
      locationDescription: 'Lincoln compound – plant cage',
      postcode: 'LN1 1YL',
      currentJobId: 'job-2',
      jobAssignedAt: '2026-09-25T07:30:00.000Z',
      quantity: 1,
      reorderLevel: null,
      notes: 'Petrol disc cutter – diamond blade fitted.',
      createdAt: now,
    },
    {
      id: 'asset-10',
      name: 'Crowbar set (assorted)',
      sku: 'HND-CRB-001',
      category: 'Hand tools',
      condition: 'Good',
      fuelTankLitres: null,
      fuelLevelLitres: null,
      locationLat: null,
      locationLng: null,
      locationDescription: 'Tool store – Rack C',
      postcode: 'NG9 2HQ',
      currentJobId: null,
      jobAssignedAt: null,
      quantity: 12,
      reorderLevel: 4,
      notes: '18–36 inch assorted.',
      createdAt: now,
    },
    {
      id: 'asset-11',
      name: 'Shovel & pick set',
      sku: 'HND-SHV-002',
      category: 'Hand tools',
      condition: 'Fair',
      fuelTankLitres: null,
      fuelLevelLitres: null,
      locationLat: null,
      locationLng: null,
      locationDescription: 'Tool store – Rack C',
      postcode: 'NG9 2HQ',
      currentJobId: 'job-1',
      jobAssignedAt: '2026-09-22T08:00:00.000Z',
      quantity: 8,
      reorderLevel: 3,
      notes: 'Insulated handles where marked.',
      createdAt: now,
    },
    {
      id: 'asset-12',
      name: 'Tarmac cold-lay bags 25kg',
      sku: 'BLD-TAR-001',
      category: 'Building products',
      condition: 'Good',
      fuelTankLitres: null,
      fuelLevelLitres: null,
      locationLat: null,
      locationLng: null,
      locationDescription: 'Materials bay – Covered store',
      postcode: 'NG9 2HQ',
      currentJobId: null,
      jobAssignedAt: null,
      quantity: 48,
      reorderLevel: 20,
      notes: 'Instant Road Repair brand.',
      createdAt: now,
    },
    {
      id: 'asset-13',
      name: 'Concrete postmix 20kg',
      sku: 'BLD-CON-002',
      category: 'Building products',
      condition: 'Good',
      fuelTankLitres: null,
      fuelLevelLitres: null,
      locationLat: null,
      locationLng: null,
      locationDescription: 'Materials bay – Covered store',
      postcode: 'NG9 2HQ',
      currentJobId: null,
      jobAssignedAt: null,
      quantity: 30,
      reorderLevel: 15,
      notes: 'Rapid-set for sign posts.',
      createdAt: now,
    },
    {
      id: 'asset-14',
      name: 'Diesel (bulk depot)',
      sku: 'CON-DSL-001',
      category: 'Consumables',
      condition: 'Good',
      fuelTankLitres: null,
      fuelLevelLitres: null,
      locationLat: null,
      locationLng: null,
      locationDescription: 'Depot fuel bowser',
      postcode: 'NG9 2HQ',
      currentJobId: null,
      jobAssignedAt: null,
      quantity: 2400,
      reorderLevel: 800,
      notes: 'Litres remaining in bowser. Red diesel marked.',
      createdAt: now,
    },
    {
      id: 'asset-15',
      name: 'Cable ties & duct tape pack',
      sku: 'CON-CTD-002',
      category: 'Consumables',
      condition: 'Excellent',
      fuelTankLitres: null,
      fuelLevelLitres: null,
      locationLat: null,
      locationLng: null,
      locationDescription: 'Stores counter',
      postcode: 'NG9 2HQ',
      currentJobId: null,
      jobAssignedAt: null,
      quantity: 25,
      reorderLevel: 10,
      notes: 'Assorted packs.',
      createdAt: now,
    },
  ];

  const jobs = [
    {
      id: 'job-1',
      title: 'A52 dual carriageway resurfacing',
      customerId: 'cust-1',
      status: 'In progress',
      startDate: '2026-09-22',
      endDate: '2026-10-10',
      requiredAssetIds: ['asset-1', 'asset-11', 'asset-12'],
      location: 'A52 between Bramcote & Dunkirk, NG9',
      notes: 'Night works Thu–Sun. Chapter 8 traffic management in place.',
      createdAt: now,
    },
    {
      id: 'job-2',
      title: 'A15 drainage & verge clearance',
      customerId: 'cust-2',
      status: 'In progress',
      startDate: '2026-09-25',
      endDate: '2026-10-05',
      requiredAssetIds: ['asset-2', 'asset-7', 'asset-9'],
      location: 'A15 Lincoln to Sleaford corridor',
      notes: 'Daytime lane closures. Ecology check completed.',
      createdAt: now,
    },
    {
      id: 'job-3',
      title: 'M1 J28–J32 earthworks support',
      customerId: 'cust-3',
      status: 'In progress',
      startDate: '2026-09-20',
      endDate: '2026-11-15',
      requiredAssetIds: ['asset-4'],
      location: 'M1 compound, LS11',
      notes: 'Plant hire only – operator supplied by client.',
      createdAt: now,
    },
    {
      id: 'job-4',
      title: 'Street lighting column replacements',
      customerId: 'cust-4',
      status: 'Planned',
      startDate: '2026-10-06',
      endDate: '2026-10-20',
      requiredAssetIds: ['asset-3', 'asset-6'],
      location: 'Birmingham outer ring, B1–B29',
      notes: 'Awaiting permit confirmation.',
      createdAt: now,
    },
    {
      id: 'job-5',
      title: 'Emergency pothole repairs – Area 7',
      customerId: 'cust-1',
      status: 'Planned',
      startDate: '2026-10-01',
      endDate: '2026-10-03',
      requiredAssetIds: ['asset-1', 'asset-12'],
      location: 'Various – Area 7 call-outs',
      notes: 'Reactive framework call-off.',
      createdAt: now,
    },
  ];

  const fuelLogs = [
    { id: 'fuel-1', assetId: 'asset-1', date: '2026-09-20', litres: 120, costGbp: 168.0, odometerOrHours: 142350, notes: 'Depot bowser', createdAt: now },
    { id: 'fuel-2', assetId: 'asset-1', date: '2026-09-26', litres: 80, costGbp: 112.4, odometerOrHours: 142680, notes: 'Site top-up', createdAt: now },
    { id: 'fuel-3', assetId: 'asset-2', date: '2026-09-24', litres: 45, costGbp: 67.5, odometerOrHours: 48210, notes: 'Shell Digbeth', createdAt: now },
    { id: 'fuel-4', assetId: 'asset-3', date: '2026-09-18', litres: 50, costGbp: 72.0, odometerOrHours: 22100, notes: 'Depot', createdAt: now },
    { id: 'fuel-5', assetId: 'asset-4', date: '2026-09-21', litres: 60, costGbp: 84.0, odometerOrHours: 1850, notes: 'Hours meter', createdAt: now },
    { id: 'fuel-6', assetId: 'asset-4', date: '2026-09-27', litres: 40, costGbp: 56.0, odometerOrHours: 1892, notes: 'Compound bowser', createdAt: now },
    { id: 'fuel-7', assetId: 'asset-6', date: '2026-09-15', litres: 70, costGbp: 98.0, odometerOrHours: 420, notes: 'Full tank', createdAt: now },
  ];

  const maintenance = [
    { id: 'mnt-1', assetId: 'asset-1', type: 'Service', date: '2026-08-12', nextDue: '2027-02-12', result: 'Pass', notes: 'Full service + brake check', createdAt: now },
    { id: 'mnt-2', assetId: 'asset-1', type: 'MOT', date: '2026-03-01', nextDue: '2027-03-01', result: 'Pass', notes: 'Class 7 MOT', createdAt: now },
    { id: 'mnt-3', assetId: 'asset-2', type: 'MOT', date: '2025-11-20', nextDue: '2026-11-20', result: 'Pass', notes: 'No advisories', createdAt: now },
    { id: 'mnt-4', assetId: 'asset-2', type: 'Service', date: '2026-06-01', nextDue: '2026-12-01', result: 'Pass', notes: 'Oil & filters', createdAt: now },
    { id: 'mnt-5', assetId: 'asset-3', type: 'LOLER', date: '2026-05-10', nextDue: '2026-11-10', result: 'Pass', notes: 'Thorough examination', createdAt: now },
    { id: 'mnt-6', assetId: 'asset-3', type: 'MOT', date: '2026-01-15', nextDue: '2027-01-15', result: 'Pass', notes: '', createdAt: now },
    { id: 'mnt-7', assetId: 'asset-4', type: 'Service', date: '2026-07-01', nextDue: '2027-01-01', result: 'Pass', notes: '500-hour service', createdAt: now },
    { id: 'mnt-8', assetId: 'asset-5', type: 'Service', date: '2026-02-20', nextDue: '2026-08-20', result: 'Pass', notes: 'OVERDUE – vibration issue noted', createdAt: now },
    { id: 'mnt-9', assetId: 'asset-7', type: 'PAT', date: '2025-10-05', nextDue: '2026-10-05', result: 'Pass', notes: 'Due soon', createdAt: now },
    { id: 'mnt-10', assetId: 'asset-8', type: 'PAT', date: '2026-01-10', nextDue: '2027-01-10', result: 'Pass', notes: 'All three units', createdAt: now },
    { id: 'mnt-11', assetId: 'asset-9', type: 'PAT', date: '2025-09-01', nextDue: '2026-09-01', result: 'Fail', notes: 'OVERDUE – failed lead inspection, awaiting retest', createdAt: now },
    { id: 'mnt-12', assetId: 'asset-6', type: 'Service', date: '2026-04-18', nextDue: '2026-10-18', result: 'Pass', notes: 'Annual service', createdAt: now },
  ];

  const bookings = [
    { id: 'book-1', assetId: 'asset-1', jobId: 'job-1', startDate: '2026-09-22', endDate: '2026-10-10', notes: 'Primary tipper', createdAt: now },
    { id: 'book-2', assetId: 'asset-2', jobId: 'job-2', startDate: '2026-09-25', endDate: '2026-10-05', notes: 'Crew van', createdAt: now },
    { id: 'book-3', assetId: 'asset-4', jobId: 'job-3', startDate: '2026-09-20', endDate: '2026-11-15', notes: 'Excavator hire', createdAt: now },
    { id: 'book-4', assetId: 'asset-3', jobId: 'job-4', startDate: '2026-10-06', endDate: '2026-10-20', notes: 'Cherry picker for columns', createdAt: now },
    { id: 'book-5', assetId: 'asset-6', jobId: 'job-4', startDate: '2026-10-06', endDate: '2026-10-20', notes: 'Site power', createdAt: now },
    { id: 'book-6', assetId: 'asset-1', jobId: 'job-5', startDate: '2026-10-01', endDate: '2026-10-03', notes: 'Conflict window with job-1 – review needed', createdAt: now },
    { id: 'book-7', assetId: 'asset-7', jobId: 'job-2', startDate: '2026-09-25', endDate: '2026-10-05', notes: '', createdAt: now },
    { id: 'book-8', assetId: 'asset-5', jobId: null, startDate: '2026-10-12', endDate: '2026-10-18', notes: 'Internal training / reserved', createdAt: now },
  ];

  return {
    customers,
    assets,
    jobs,
    fuelLogs,
    maintenance,
    bookings,
    settings: {
      companyName: 'Midlands Highways Plant Ltd',
      currency: 'GBP',
      lowFuelThresholdPercent: 25,
      theme: 'light',
    },
  };
}
